import type { Metadata } from "next";
import "./globals.css";
import { PageTransitionProvider } from "@/contexts/PageTransitionContext";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-[url('../../public/imgs/bg.png')] bg-cover bg-center ">
<Script
  src="https://unpkg.com/@lottiefiles/dotlottie-wc@0.6.2/dist/dotlottie-wc.js"
  type="module"
  strategy="beforeInteractive"
/>
        <PageTransitionProvider>{children}</PageTransitionProvider>
      </body>
    </html>
  );
}
