import type { Metadata } from "next";
import "./globals.css";
import PageTransition from "../../Animation/PageTransition";
import { PageTransitionProvider } from "../../contexts/PageTransitionContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-[url('../../public/imgs/bg.png')] bg-cover bg-center px-5">
        <PageTransitionProvider>
          {children}
        </PageTransitionProvider>
      </body>
    </html>
  );
}
